/**
 * JARVIS Personalization — Learning Signals
 *
 * Trusted server-side event collector. Only events generated by the pipeline
 * or verified tool executions create signals. The model cannot fabricate signals.
 */

import { randomUUID } from "crypto";

import { type LearningSignal, type SignalType, PERSONALIZATION_LIMITS } from "./types";
import { validateSignalInput } from "./validator";

/**
 * Create a learning signal from a trusted event.
 * Returns null if validation fails.
 */
export function createSignal(
  type: SignalType,
  metric: string,
  metadata?: Record<string, unknown>,
): LearningSignal | null {
  const validation = validateSignalInput({ type, metric });
  if (!validation.valid || !validation.data) return null;

  return {
    id: randomUUID(),
    type: validation.data.type as SignalType,
    metric: validation.data.metric,
    timestamp: Date.now(),
    metadata,
  };
}

/**
 * Trim a signal array to the bounded limit (keep most recent).
 */
export function trimSignals(signals: LearningSignal[]): LearningSignal[] {
  return signals.slice(-PERSONALIZATION_LIMITS.MAX_SIGNALS);
}

/**
 * Aggregate signals by type and metric into counts.
 */
export function aggregateSignals(signals: LearningSignal[]): Map<string, number> {
  const counts = new Map<string, number>();
  for (const signal of signals) {
    const key = `${signal.type}:${signal.metric}`;
    counts.set(key, (counts.get(key) ?? 0) + 1);
  }
  return counts;
}

/**
 * Count signals of a specific type within a time window.
 */
export function countRecentSignals(
  signals: LearningSignal[],
  type: SignalType,
  windowMs: number,
): number {
  const cutoff = Date.now() - windowMs;
  return signals.filter((s) => s.type === type && s.timestamp >= cutoff).length;
}
